# Generated by Django 5.0.14 on 2026-05-26 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_id', models.IntegerField(db_index=True)),
                ('workflow_type', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_id', models.IntegerField(db_index=True)),
                ('approver_id', models.IntegerField(db_index=True)),
                ('action', models.CharField(max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('approver_id', models.IntegerField(db_index=True)),
                ('role_required', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='steps', to='approvals.approvalchain')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('chain', 'order')},
            },
        ),
    ]
