# Generated by Django 5.0.14 on 2026-06-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalrecord',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='approvalstep',
            options={'ordering': ['step_number']},
        ),
        migrations.RenameField(
            model_name='approvalrecord',
            old_name='approver_id',
            new_name='actor_id',
        ),
        migrations.RenameField(
            model_name='approvalstep',
            old_name='order',
            new_name='step_number',
        ),
        migrations.RemoveField(
            model_name='approvalchain',
            name='name',
        ),
        migrations.RemoveField(
            model_name='approvalchain',
            name='workflow_type',
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together={('chain', 'step_number')},
        ),
        migrations.AddField(
            model_name='approvalchain',
            name='current_step_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='approvalchain',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalchain',
            name='documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='approvalchain',
            name='status',
            field=models.CharField(
                choices=[
                    ('active',
                     'Active'),
                    ('approved',
                     'Approved'),
                    ('rejected',
                     'Rejected'),
                    ('returned',
                     'Returned for Changes')],
                db_index=True,
                default='active',
                max_length=20),
        ),
        migrations.AddField(
            model_name='approvalchain',
            name='student_faculty',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='approvalchain',
            name='student_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalchain',
            name='student_matricule',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='approvalchain',
            name='student_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='approvalchain',
            name='total_steps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvalchain',
            name='workflow_type_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='actor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='annotated_document',
            field=models.FileField(blank=True, null=True, upload_to='annotated_docs/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='send_feedback_to_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='step_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='assignee_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='assignee_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='has_annotated_document',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='role_display_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approvalchain',
            name='workflow_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='approvalrecord',
            name='action',
            field=models.CharField(
                choices=[
                    ('approved',
                     'Approved'),
                    ('rejected',
                     'Rejected'),
                    ('returned',
                     'Returned for Changes'),
                    ('reassigned',
                     'Reassigned'),
                    ('commented',
                     'Commented')],
                max_length=20),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='role_required',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending',
                     'Pending'),
                    ('active',
                     'Active'),
                    ('approved',
                     'Approved'),
                    ('rejected',
                     'Rejected'),
                    ('returned',
                     'Returned for Changes'),
                    ('reassigned',
                     'Reassigned'),
                    ('void',
                     'Void')],
                db_index=True,
                default='pending',
                max_length=20),
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='approver_id',
        ),
    ]
