# Generated by Django 5.0.14 on 2026-06-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_alter_approvalrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrecord',
            name='approver_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='send_to_submitter',
            field=models.BooleanField(default=False),
        ),
    ]
