# Generated by Django 5.0.14 on 2026-06-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_approvalrecord_approver_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalchain',
            name='appeal_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='approvalchain',
            name='appeal_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvalchain',
            name='original_rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='approver_signature_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='approver_stamp_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='comments_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
