sonar.projectKey=flowdesk
sonar.projectName=FlowDesk
sonar.sources=services/auth-service/apps,services/workflow-service/apps,services/approval-service/apps,services/notification-service/apps,services/analytics-service/apps
sonar.tests=services/auth-service/tests,services/workflow-service/tests,services/approval-service/tests,services/notification-service/tests,services/analytics-service/tests
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/*.pyc,**/venv/**,**/.pytest_cache/**,**/pytest-cache-files-*/**
sonar.coverage.exclusions=**/config/**,**/migrations/**,**/tests/**,**/__init__.py,**/admin.py,**/apps.py,**/urls.py,**/asgi.py,**/wsgi.py,**/celery.py
sonar.python.version=3
sonar.python.coverage.reportPaths=coverage-auth-service.xml,coverage-workflow-service.xml,coverage-approval-service.xml,coverage-notification-service.xml,coverage-analytics-service.xml
