sonar.projectKey=flowdesk
sonar.projectName=FlowDesk
sonar.sources=services
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/tests/**,**/*.pyc
sonar.python.version=3
sonar.python.coverage.reportPaths=coverage.xml
