sonar.projectKey=flowdesk
sonar.projectName=FlowDesk
sonar.sources=services
sonar.tests=services
sonar.test.inclusions=**/tests/**
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/tests/**,**/*.pyc,**/venv/**,**/.pytest_cache/**,**/pytest-cache-files-*/**
sonar.coverage.exclusions=**/config/**,**/migrations/**,**/tests/**,**/__init__.py,**/admin.py,**/apps.py,**/urls.py,**/asgi.py,**/wsgi.py,**/celery.py
sonar.python.version=3
sonar.python.coverage.reportPaths=coverage-auth-service.xml,coverage-workflow-service.xml,coverage-approval-service.xml,coverage-notification-service.xml,coverage-analytics-service.xml
