# Generated by Django 5.0.14 on 2026-06-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowauth', '0002_customuser_faculty_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approver_type',
            field=models.CharField(blank=True, choices=[('registrar', 'Registrar'), ('dean', 'Dean'), ('hod', 'Head of Department'), ('admin_assistant', 'Administrative Assistant'), ('faculty_council', 'Faculty Scientific Council'), ('dvc', 'Deputy Vice Chancellor'), ('supervisor', 'Supervisor')], db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rolechangelog',
            name='new_approver_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='rolechangelog',
            name='old_approver_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
