# Generated by Django 5.0.14 on 2026-06-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowauth', '0003_customuser_approver_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stamp_image',
            field=models.ImageField(blank=True, null=True, upload_to='stamps/'),
        ),
    ]
