apiVersion: v1
kind: Secret
metadata:
  name: flowdesk-secrets
  namespace: flowdesk
type: Opaque
stringData:
  DJANGO_SECRET_KEY: change-me
  JWT_SECRET_KEY: change-me
  DATABASE_URL_AUTH: postgresql://flowdesk:flowdesk@postgres:5432/flowdesk_db?options=-csearch_path=auth_svc
  DATABASE_URL_WORKFLOW: postgresql://flowdesk:flowdesk@postgres:5432/flowdesk_db?options=-csearch_path=workflow_svc
  DATABASE_URL_APPROVAL: postgresql://flowdesk:flowdesk@postgres:5432/flowdesk_db?options=-csearch_path=approval_svc
  DATABASE_URL_NOTIFICATION: postgresql://flowdesk:flowdesk@postgres:5432/flowdesk_db?options=-csearch_path=notification_svc
  DATABASE_URL_ANALYTICS: postgresql://flowdesk:flowdesk@postgres:5432/flowdesk_db?options=-csearch_path=analytics_svc,approval_svc,workflow_svc,auth_svc
