# Generated by Django 5.0.14 on 2026-06-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='workflow_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
