# Generated by Django 5.0.8 on 2026-05-26 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("approvals", "0001_initial"),
        ("workflows", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrecord",
            name="approver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="approvalrecord",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_records",
                to="workflows.workflow",
            ),
        ),
        migrations.AddField(
            model_name="approvalstep",
            name="approver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="approvalstep",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="approvals.approvalchain",
            ),
        ),
        migrations.AddField(
            model_name="approvalchain",
            name="workflow_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chains",
                to="approvals.approvaltype",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrecord",
            index=models.Index(
                fields=["workflow", "-created_at"],
                name="approvals_a_workflo_173b22_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="approvalstep",
            unique_together={("chain", "order")},
        ),
    ]
