# Generated by Django 5.0.14 on 2026-05-26 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_id', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('preview_cache_key', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_approval', 'In Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('sla_status', models.CharField(choices=[('on_track', 'On Track'), ('warning_50', '50% Deadline'), ('warning_75', '75% Deadline'), ('overdue', 'Overdue')], db_index=True, default='on_track', max_length=20)),
                ('created_by_id', models.IntegerField(db_index=True)),
                ('assigned_to_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='workflows_w_status_f64426_idx'), models.Index(fields=['created_by_id', 'status'], name='workflows_w_created_e9b9ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('extracted_text', models.TextField(blank=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='workflows.workflow')),
            ],
        ),
    ]
