# Generated by Django 5.0.8 on 2026-05-29 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="all_documents_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workflow",
            name="approval_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="workflow",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="workflow",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="workflow",
            name="priority",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="workflow",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="WorkflowDocumentRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_slug", models.CharField(max_length=120)),
                ("label", models.CharField(blank=True, max_length=255)),
                ("is_required", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_requirements",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {("workflow", "document_slug")},
            },
        ),
        migrations.CreateModel(
            name="ApprovalStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_stops",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("workflow", "order")},
            },
        ),
        migrations.CreateModel(
            name="WorkflowDocumentUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="workflow-requirements/%Y/%m/%d/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("verified", models.BooleanField(default=False)),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to="workflows.workflowdocumentrequirement",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_uploads",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["workflow_instance", "requirement"],
                        name="workflows_w_workflo_2ed07d_idx",
                    ),
                    models.Index(
                        fields=["verified"], name="workflows_w_verifie_aeaad5_idx"
                    ),
                ],
            },
        ),
    ]
