# Generated by Django 5.0.8 on 2026-05-30 18:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0002_workflow_all_documents_required_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowConfigUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_by_id", models.IntegerField()),
                ("file", models.FileField(upload_to="workflow_config/%Y/%m/%d/")),
                ("created", models.PositiveIntegerField(default=0)),
                ("updated", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("approval_type", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("department", models.CharField(blank=True, max_length=200)),
                ("priority", models.PositiveSmallIntegerField(default=2)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("required_docs", models.JSONField(blank=True, default=list)),
                ("form_fields", models.JSONField(blank=True, default=list)),
                ("approval_chain", models.JSONField(blank=True, default=list)),
                ("all_documents_required", models.BooleanField(default=True)),
                ("expected_output", models.TextField(blank=True)),
                ("sla_days", models.PositiveIntegerField(default=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="document_label",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="document",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workflow",
            name="form_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="workflow",
            name="student_faculty",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="workflow",
            name="student_matricule",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="workflow",
            name="student_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="workflow",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="workflow_docs/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="document",
            name="filename",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="document",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="workflows.workflow",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="name",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("in_approval", "In Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("returned", "Returned for Changes"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="workflow_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workflows",
                to="workflows.workflowtype",
            ),
        ),
    ]
