# Generated by Django 5.0.14 on 2026-06-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_workflowconfigupload_workflowtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='appeal_round',
            field=models.IntegerField(default=0),
        ),
    ]
