# Generated by Django 5.0.8 on 2026-05-26 19:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("approvals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "Word"),
                            ("xlsx", "Excel"),
                            ("csv", "CSV"),
                            ("image", "Image"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "docx", "xlsx", "csv", "png", "jpg", "jpeg"]
                            )
                        ],
                    ),
                ),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("extracted_text", models.TextField(blank=True)),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("page_count", models.IntegerField(blank=True, null=True)),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("in_approval", "In Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "sla_status",
                    models.CharField(
                        choices=[
                            ("on_track", "On Track"),
                            ("warning_50", "50% Deadline"),
                            ("warning_75", "75% Deadline"),
                            ("overdue", "Overdue"),
                        ],
                        db_index=True,
                        default="on_track",
                        max_length=20,
                    ),
                ),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("priority", models.IntegerField(default=1)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflows",
                        to="approvals.approvaltype",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflows_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflows_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow",
                        to="workflows.document",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="workflows_w_status_f64426_idx",
                    ),
                    models.Index(
                        fields=["assigned_to", "status"],
                        name="workflows_w_assigne_d22c02_idx",
                    ),
                    models.Index(
                        fields=["deadline", "status"],
                        name="workflows_w_deadlin_44dc72_idx",
                    ),
                ],
            },
        ),
    ]
