CREATE SCHEMA IF NOT EXISTS auth_svc;
CREATE SCHEMA IF NOT EXISTS workflow_svc;
CREATE SCHEMA IF NOT EXISTS approval_svc;
CREATE SCHEMA IF NOT EXISTS notification_svc;
CREATE SCHEMA IF NOT EXISTS analytics_svc;

CREATE EXTENSION IF NOT EXISTS vector;
